spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:55005/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
